# Uncomment this line to define a global platform for your project
platform :ios, "5.1"

xcodeproj 'UIAlertView-BlocksDemo'
workspace 'UIAlertView-BlocksDemo'

pod 'UIAlertView-Blocks', :path => '..'
